In [3]:
import numpy as np
a=np.array([1,2,3,4,5,10])
print (a)
print (type(a))
"""explicityly we are giving a list and numpy is converting into an array of package-numpy.ndarray"""

[ 1  2  3  4  5 10]
<class 'numpy.ndarray'>


'explicityly we are giving a list and numpy is converting into an array of package-numpy.ndarray'

In [11]:
"""How to prove numpy is faster that builtin data structure of python ?"""
#lets see time taken by list for an operation
l1=list(range (100))
print (l1)
%timeit a=list(i**2 for i in l1)
"""it takes 71.1 micro seconds to yield"""

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
81.8 µs ± 4.64 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


'it takes 71.1 micro seconds to yield'

In [17]:
"""Lets calucate %timeit for array using numpy"""
ar1=np.arange(100)
ar1
%timeit [i**2 for i in ar1]
#numpy array takes atleast half the time as of LISTS


39.8 µs ± 8.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [19]:
%timeit ar1**2

1.32 µs ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [24]:
#creation of array in numpy and basic methods
ar1=np.array([1,2,3,4,5])
ar1


array([1, 2, 3, 4, 5])

In [25]:
ar2=np.arange(10)
ar2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#dimension- 1d array
ar2.ndim


1

In [30]:
#shape of array
ar2.shape


(10,)

In [31]:
#length of array- always gives the length of the first array,since it is a vector, total elements in 1st row is 10
len(ar2)

10

In [18]:
x=np.array([[[1,2,4]]])
print ("dimension: {}".format(x.ndim))
x.shape

dimension: 3


(1, 1, 3)

In [40]:
#multidimension array
ar3=np.array([[1,2,4],[1,4,16],[1,16,256]])
print (ar3)
print (ar3.ndim)#gives the dimension, vector or tensor 
print (ar3.shape)# shape tell us number of rows and columns-m and n say -it contains the size along all axes 
print (len(ar3)) #length gives total number of elements i.e. m*n NOOOO len only returns the size along the first axis:

[[  1   2   4]
 [  1   4  16]
 [  1  16 256]]
2
(3, 3)
3


In [39]:
#3dimensional array
ar4=np.array([[[1,2],[1,4]],[[1,4],[1,9]]])
print (ar4)
print (ar4.ndim)
print (len(ar4))
print (ar4.shape)

[[[1 2]
  [1 4]]

 [[1 4]
  [1 9]]]
3
2
(2, 2, 2)


In [41]:
print (np.arange(1,10,2)) #start=1, stop-10, step size-2


[1 3 5 7 9]


In [47]:
"""array creation in numpy using linear space"""
#linspace provides evenly spaced intervals between two points 
ar=np.linspace(10,100,10)
print (ar)
ar1=np.linspace(10,100,10,endpoint=False) #endpoint is false so stop will not be included
print (ar1)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[10. 19. 28. 37. 46. 55. 64. 73. 82. 91.]


In [59]:
"""common arrays"""
arzero=np.zeros((2,3))
print (arzero)
print (arzero.ndim)
print (arzero.shape)
print (len(arzero))
"""Data type for common arrays is always float 64 byte"""

[[0. 0. 0.]
 [0. 0. 0.]]
2
(2, 3)
2


In [57]:

"""Now creating an array of elements containing one"""
arones=np.ones((3,2)) #common arrays function always takes tuple as parameter and creates 2d array 
print (arones)
print (arones.ndim)
print (arones.shape)
print (len(arones))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
2
(3, 2)
3


In [78]:
"""Identity matrix"""
I=np.eye(3)
print (I)
print (I.ndim)
print (len(I))
print("___________________________________________________________________")
"""from top left to bottom right Identity matrix is created diagonally based on the dimension"""
I1=np.eye(3,4)
print (I1)
"""rest other elements of the matrix are represent as float of 64 bit"""
print (I1.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2
3
___________________________________________________________________
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
float64


In [79]:
"""Creating a diagonal matrix"""
"""np.diag creates a diagonal matrix based on the elements provided in the form of a List"""
D1=np.diag([1,2,4,16,256])
print (D1)
print (D1.ndim)
print (D1.shape)
print (len(D1))
print (D1.dtype)
"""All other values other than diagonal elements are zeros"""

[[  1   0   0   0   0]
 [  0   2   0   0   0]
 [  0   0   4   0   0]
 [  0   0   0  16   0]
 [  0   0   0   0 256]]
2
(5, 5)
5
int32


'All other values other than diagonal elements are zeros'

In [73]:
"""Creating a random array"""
r1=np.random.rand(6)
print (r1) #print function just represent the value in the list, not seprated with comma, we use repr() to get CSV
r1

#random is a module and rand is a function

[0.21256176 0.62025996 0.65383541 0.4251817  0.17507767 0.6138684 ]


array([0.21256176, 0.62025996, 0.65383541, 0.4251817 , 0.17507767,
       0.6138684 ])

In [75]:
r2=np.random.rand(8)
print (repr(r2))#print function just represent the value in the list, not seprated with comma, we use repr() to get CSV
r2

array([0.37880116, 0.74645425, 0.08099948, 0.44556919, 0.23986545,
       0.99790599, 0.4871304 , 0.37237074])


array([0.37880116, 0.74645425, 0.08099948, 0.44556919, 0.23986545,
       0.99790599, 0.4871304 , 0.37237074])

In [83]:
"""Understanding even of Numpy"""
ar1=np.arange(8) #by default, ap.arange has ddtype as int 
print (repr(ar1))
print (ar1.dtype)
ar2=np.arange(10, dtype='float')
print (repr(ar2))
print (ar2.dtype)



array([0, 1, 2, 3, 4, 5, 6, 7])
int32
array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
float64


'Complex dtype array'

In [88]:
"""Complex dtype array"""
c1=np.array([1+2j,2+4j])
print (c1)
c1.dtype

[1.+2.j 2.+4.j]


dtype('complex128')

In [92]:
"""How to access elements in numpy.ndarray"""
ar1=np.array([1,2,4,5,6])
print (ar1)
ar1[3]



[1 2 4 5 6]


5

In [94]:
"""In a 2d array"""
d1=np.diag([1,2,3,4,5])
print (repr(d1))
print (d1[2][2])
d1[3][3]=101
print (repr(d1))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])
3
array([[  1,   0,   0,   0,   0],
       [  0,   2,   0,   0,   0],
       [  0,   0,   3,   0,   0],
       [  0,   0,   0, 101,   0],
       [  0,   0,   0,   0,   5]])


In [99]:
a1=np.random.rand(5)
print (repr(a1))
print (a1[2:])
print (a1[1:4:2])


array([0.255494  , 0.5817411 , 0.93202901, 0.35168117, 0.15199915])
[0.93202901 0.35168117 0.15199915]
[0.5817411  0.35168117]


In [103]:
a=np.arange(5)
b=a[::-1]
b

array([4, 3, 2, 1, 0])

In [119]:
"""Copies and views in array"""
"""Numpy avoids creation of different array for the same purpose """
a=np.arange(10,110,10)
print (repr(a))
b=a[0:9:4]
"""since b is being created from an array pointed by a in RAM, numpy don't allow to create a different array,
istead numpy helps to genereate a view for array with name b"""
print (repr(b))
print (np.shares_memory(a,b))
print('____________________________-')
b[1]=999
print (repr(b))
print (repr(a)) #since a and b shares same part of memory, change in b get a updated ! Bingooooooo
print ('_____________________________________')
print (id(a))
print (id (b))
print ('_____________________________________')


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
array([10, 50, 90])
True
____________________________-
array([ 10, 999,  90])
array([ 10,  20,  30,  40, 999,  60,  70,  80,  90, 100])
_____________________________________
1294189919488
1294189919648
_____________________________________


In [127]:
"""TO avoid similar condition, we use copy fucntion"""
a=np.arange(3,30,3)
print (repr(a))
b=a[4::-1].copy()
print (repr(b))
print (np.shares_memory(a,b))

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])
array([15, 12,  9,  6,  3])
False


In [154]:
"""Fancy indexing"""
a=np.random.randint(1,100,10)
print (repr(a))
mask=[a%2==0]
print (repr(mask))
print (type(mask))
print (type(mask[0]))
print ('Does a and mask share the same memory: {}'.format(np.shares_memory(a,mask)))
even=a[mask]
print (repr(even))
print ('Does a and even share the same memory: {}'.format(np.shares_memory(a,even)))
"""Mask creates copies and not the views, hence even being the subarray of a, they don't share memory !"""

array([94, 80, 74, 20, 63, 76, 81, 93, 44,  5])
[array([ True,  True,  True,  True, False,  True, False, False,  True,
       False])]
<class 'list'>
<class 'numpy.ndarray'>
Does a and mask share the same memory: False
array([94, 80, 74, 20, 76, 44])
Does a and even share the same memory: False


C:\Users\Ankesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  if __name__ == '__main__':


"Mask creates copies and not the views, hence even being the subarray of a, they don't share memory !"

In [161]:
a=np.random.randint(1,100,10)
print (repr(a))
print (repr(a[[1,3,4,5]]))
a[[2,3,7,5]]=-3000
a

array([41, 17, 22, 52, 78, 89, 47, 89,  6, 57])
array([17, 52, 78, 89])


array([   41,    17, -3000, -3000,    78, -3000,    47, -3000,     6,
          57])

In [172]:
"""Numerical operations in array"""
a=np.arange(1,10,1)
print (repr(a))
a+=10
print (repr(a))
b=np.arange(2,20,2)
print (repr(b))
print (repr(a-b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array([11, 12, 13, 14, 15, 16, 17, 18, 19])
array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])
array([9, 8, 7, 6, 5, 4, 3, 2, 1])


In [192]:
"""Multiplication of arrays"""
a1=np.ones((4,4))
print (repr(a1))
a2=np.diag([1,2,4,5])
print (repr(a2))
print (a1.dot(a2))
print (a1*a2)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])
[[1. 2. 4. 5.]
 [1. 2. 4. 5.]
 [1. 2. 4. 5.]
 [1. 2. 4. 5.]]
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 5.]]


In [198]:
"""Bitwise operation"""
a=np.arange(2,20,2)
print (repr(a))
b=np.arange(1,10,1)
print (repr(b))
a==b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])
array([1, 2, 3, 4, 5, 6, 7, 8, 9])


array([False, False, False, False, False, False, False, False, False])

In [200]:
print (np.array_equal(a,b)) #compares two array element wise

False


In [207]:
"""Comparing arrays logically- Logical operations"""
a1=np.array([1,1,0,0,1] ,dtype=bool)
a2=np.array([0,1,0,1,1] ,dtype=bool)
print (np.logical_and(a1,a2))
print (np.logical_or(a1,a2))



[False  True False False  True]
[ True  True False  True  True]


In [212]:
"""Transcendental functions"""

a=np.arange(5)
print (np.sin(a))
b=np.array([0,30,60,90,180])
print (np.cos(b))
print (np.log(a))
print (np.exp(a))


[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          0.15425145 -0.95241298 -0.44807362 -0.59846007]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


C:\Users\Ankesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


In [216]:
"""When we try to perform operation on two different shapes of arrays"""
a=np.array([1,3,4,5])
b=a+np.arange(1,10,1)
print (b)

ValueError: operands could not be broadcast together with shapes (4,) (9,) 

In [227]:
"""Computing sums"""

a=np.array([1,2,4,4,5,7])
print (np.sum(a))
a1=np.array([[1,2,4],[2,3,4]])
print (repr(a1))
print (a1.sum(axis=0)) #When we say axis=0, operation is performed column wise
print (a1.sum(axis=1)) #When we say axis=1, operation is performed row wise

23
array([[1, 2, 4],
       [2, 3, 4]])
[3 5 8]
[7 9]


In [231]:
"""aggregate functions"""
x=np.array([1,2,7,4,4,5])
print (x.min())
print (x.max())
print ('minimum is at index {}'.format(x.argmin()))
print ('maximum is at index {}'.format(x.argmax()))

1
7
minimum is at index 0
maximum is at index 2


In [242]:
"""Boolean"""
np.all([True, False,True]) #if all the elements are true it returns true
np.any([False, True, False]) #if any of elements is true it return true

x=np.ones((3,4))
print (repr(x))
print (np.any(x!=0))
print (np.any(x!=1))
print (np.all(x==1))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
True
False
True


In [253]:
a=np.array([1,10,4,5])
b=np.array([2,3,4,5])
c=np.ones(4)
print (a>b.any())
print (repr(c))
print (((a & b)>c).any())

[False  True  True  True]
array([1., 1., 1., 1.])
True


In [260]:
"""Statistics"""
x=np.arange(1,10,2)
print (repr(x))
print(x.mean())
print (np.median(x))
y=np.array([[1,2,4],[5,6,2]])
print (np.median(y))
print (x.std()) #standard deviation




array([1, 3, 5, 7, 9])
5.0
5.0
3.0
2.8284271247461903


In [356]:
"""Loading dataset in numpy"""
data=np.loadtxt('population.txt')
print (data)
print (type(data))

[[ 1901.  3000.  4000. 45049.]
 [ 1903.  4000.  5200. 34552.]
 [ 1905.  3422.  5643. 12345.]
 [ 1906.  3413.  2345. 19999.]]
<class 'numpy.ndarray'>


In [274]:
Year, Hares, Lynx, Carrot=data.T
print (Year)

[1901. 1903. 1905. 1906.]


In [357]:
population=data[:,1] #slicing involves comma
population

array([3000., 4000., 3422., 3413.])

In [280]:
population=data[:,1:]
population

array([[ 3000.,  4000., 45049.],
       [ 4000.,  5200., 34552.],
       [ 3422.,  5643., 12345.],
       [ 3413.,  2345., 19999.]])

In [281]:
population.mean()

11914.0

In [284]:
population.mean(axis=0) #taking the mean column wise


array([ 3458.75,  4297.  , 27986.25])

In [287]:
"""to check which year it has the maximum population"""
np.argmax(population,axis=1) #axis=1 applies row wise and returns the index of the column this has max values, here carrot in 
                                #in all the rows

array([2, 2, 2, 2], dtype=int64)

In [288]:
np.argmin(population,axis=0) 

array([0, 3, 2], dtype=int64)

In [292]:
"""Concept of broadcasting:
It is the process of creating a replica to perform certain operations in a matrix"""
a1=np.tile(np.arange(20,100,10),(3,2)) #2nd argumnet 3,2-adds 2rows and 1 column extra as replica
a1



array([[20, 30, 40, 50, 60, 70, 80, 90, 20, 30, 40, 50, 60, 70, 80, 90],
       [20, 30, 40, 50, 60, 70, 80, 90, 20, 30, 40, 50, 60, 70, 80, 90],
       [20, 30, 40, 50, 60, 70, 80, 90, 20, 30, 40, 50, 60, 70, 80, 90]])

In [299]:
a2=np.tile(np.arange(1,5,1),(3,1)) #replicate 3 times in the row and just one time in the column
print (a2)
print ('__________________________')
a3=a2.T
print (a3) 

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
__________________________
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [300]:
"""creating another matrix to perform addition operation"""
b3=np.array([10,11,12])
b3

array([10, 11, 12])

In [301]:
"""Performing the operation now"""
print (a3+b3)

[[11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]]


In [309]:
"""np.newaxis - attribute that changes the shape of an array"""
x1=np.array([1,4,5,6,7])
print (repr(x1))
print (x1.shape) #1D array
x1=x1[:,np.newaxis] #include all the rows and create a 2D array
print (repr(x1)) #2D array
print (x1.shape)
print ('_________________________--')
x1=x1[:,np.newaxis] #include all the rows and create a 3D array now
print (repr(x1)) #3D array
print (x1.shape) 

array([1, 4, 5, 6, 7])
(5,)
array([[1],
       [4],
       [5],
       [6],
       [7]])
(5, 1)
_________________________--
array([[[1]],

       [[4]],

       [[5]],

       [[6]],

       [[7]]])
(5, 1, 1)


In [315]:
"""Array shape manipulation- Process of Flattening"""
#ravel()- property of an array which reduces its shape- from 2d to 1d
x=np.array([[1,2,3],[1,4,9]])
print(x)
print (x.shape)
print ('______________')
x=x.ravel()
print(x)
print (x.shape)
print ('______________')


[[1 2 3]
 [1 4 9]]
(2, 3)
______________
[1 2 3 1 4 9]
(6,)
______________


In [321]:
"""Inverse operation to flatenning"""
x=np.array([[1,3,5,6],[5,3,56,7]])
print (repr(x))
y=x.ravel()
print (y)
"""reshape()"""
print ('after ravel it is possible to convert back to orinial shape using reshape()')
z=y.reshape(2,4)
print (repr(z))

array([[ 1,  3,  5,  6],
       [ 5,  3, 56,  7]])
[ 1  3  5  6  5  3 56  7]
array([[ 1,  3,  5,  6],
       [ 5,  3, 56,  7]])


In [333]:
x=np.arange(4*3*2) #creates an 1d array 0f elements from 0 to 23-
print (repr(x))
x=x.reshape(4,3,2) #giving x array a shape of matrix 3,2 and diving into 4 arrays
print ('___________________________________________')
print (repr(x))
print ('Shape of array x is {}'.format(x.shape))
print ('___________________________________________')
print (x[0])
print (x[2])
print ('___________________________________________')
print (x[0][1][1]) #first matrix, 1st row, 1st column


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])
___________________________________________
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])
Shape of array x is (4, 3, 2)
___________________________________________
[[0 1]
 [2 3]
 [4 5]]
[[12 13]
 [14 15]
 [16 17]]
___________________________________________
3


In [343]:
"""Sorting of an array: """
ar=np.array([[10,7,1,66],[54,13,91,44]])
print (repr(ar))
print ('_______')
print ('sorting by row')
print (np.sort(ar,axis=1))
print ('________')
print ('sorting by column')
b=np.sort(ar,axis=0)
b

array([[10,  7,  1, 66],
       [54, 13, 91, 44]])
_______
sorting by row
[[ 1  7 10 66]
 [13 44 54 91]]
________
sorting by column


array([[10,  7,  1, 44],
       [54, 13, 91, 66]])

In [352]:
"""sorting with fancy indexing"""
"""instead of elements getting sort using np.sort or array.sort, argsort is used to sort the indices of elements instead"""
a=np.array([1,4,5,2])
print (repr(a))
b=np.argsort(a)
print (repr(b))
print ('                ')
j=np.argsort(a)
print (j)
print (repr(a[j]))

array([1, 4, 5, 2])
array([0, 3, 1, 2], dtype=int64)
                
[0 3 1 2]
array([1, 2, 4, 5])
